### PR TITLE
Bei LogicResolutionComplete "Neuberechnung" einer Musterlösung vermeiden

### LINKED ISSUE #153: bei `LogicResolutionComplete` "Neuberechnung" einer Musterlösung vermeiden?
da diese im Prinzip bereits bei der Erstellung der Instanz "mit entsteht"?

nach #152

### PR DESCRIPTION
**Pull request by nimec01**
Closes #153

### CODE REVIEW

**Comment by jvoigtlaender** [comment]
At the moment, this seems more a part of #152 than addressing #153.

**Comment by nimec01** [comment]
The latest commits should now address #153.

**Comment by jvoigtlaender** [comment]
Most or all of this: https://github.com/fmidue/logic-tasks/blob/ff2eb519365b0f9536a8090dbe08ba790de75124/src/Formula/Resolution.hs#L157-L197 would now be dead code, right?

The proposal in https://github.com/fmidue/logic-tasks/issues/153#issuecomment-2277466337 was to move it to the test suite and use it as an independent semantics check.

**Comment by nimec01** [comment]
It turns out that my implementation of `computeResSteps` did not work properly for all valid `ResolutionConfigs`. I just went ahead and removed it.

**Pull request merged**
