### PR TITLE
Add `offerUnicodeInput` setting

### PR DESCRIPTION
**Pull request by nimec01**
Default value is `False` (don't show Unicode symbols) for now.

#85

### CODE REVIEW

**Comment by jvoigtlaender** [comment]
Erschlägt das #138 komplett?

**Comment by jvoigtlaender** [comment]
From #85, what about https://github.com/fmidue/logic-tasks/issues/85#issuecomment-1892502953, i.e., having this flag also have an impact on how examples inside the task descriptions are displayed?

**Comment by nimec01** [comment]
> Erschlägt das #138 komplett?

Ja

> From #85, what about [#85 (comment)](https://github.com/fmidue/logic-tasks/issues/85#issuecomment-1892502953), i.e., having this flag also have an impact on how examples inside the task descriptions are displayed?

The only task currently affected is `SimplestFormula` (which uses an `∨` in its example). There are two possible ways to deal with this in general:
- Never use Unicode symbols in an example solution
- Use Unicode symbols if `offerUnicodeInput = True`, don't use them otherwise

**Comment by jvoigtlaender** [comment]
I would say this is the way to go:
> - Use Unicode symbols if `offerUnicodeInput = True`, don't use them otherwise

**Comment by nimec01** [comment]
Spelling error fixed in #173

**Pull request merged**
